const config = {
	userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
	concurrentOperations: 4,
	launchOptions: {
		headless: true,
		args: [
			'--no-sandbox',
			'--disable-setuid-sandbox',
			'--disable-dev-shm-usage',
			'--disable-accelerated-2d-canvas',
			'--disable-gpu',
			'--window-size=1366x768',
		],
	},
	blockedResourceTypes: [
		'image',
		'media',
		'font',
		'texttrack',
		'object',
		'beacon',
		'csp_report',
		'imageset',
	],
	skippedResources: [
		'quantserve',
		'adzerk',
		'doubleclick',
		'adition',
		'exelator',
		'sharethrough',
		'cdn.api.twitter',
		'google-analytics',
		'googletagmanager',
		'google',
		'fontawesome',
		'facebook',
		'analytics',
		'optimizely',
		'clicktale',
		'mixpanel',
		'zedo',
		'clicksor',
		'tiqcdn',
	],
};

module.exports = config;